name: Deploy react app
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "16.x" ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run: npm install
      - name: registry github user
        run: |
          git config --global user.email "alexandragalarzag@gmail.com"
          git config --global user.name "MAlexGG"
      - name: deploy the app
        run: npm run deploy
        env: 
            GREEN_DIGITAL_SKILLS: ${{ secrets.GREEN_DIGITAL_SKILLS }}